#!/bin/bash
#: Description: Sets up permissions for the i2c devices
#:      Author: Thomas Preston

udev_rules_file='/etc/udev/rules.d/51-i2c.rules'

# check if the script is being run as root
if [[ $EUID -ne 0 ]]
then
	printf 'This script must be run as root.\nExiting..\n'
	exit 1
fi

# check that the rules file doesn't already exist
if [ -f $udev_rules_file ]
then
	printf 'The i2c rules file already exists.\nExiting...\n'
	exit 1
fi


# create the rules file
printf 'Creating udev rule\n'
echo 'KERNEL=="i2cdev*", GROUP="i2cuser", MODE="0660"' > $udev_rules_file

groupadd i2cuser # create the i2cuser group
gpasswd -a pi i2cuser # add pi to the i2cuser group

printf 'User "pi" can now access the /dev/i2cdev* devices\n'
printf 'Please REBOOT for the changes to take effect\n'
